### ISSUE TITLE
please check if you published all your code

### ISSUE THREAD

**Issue by tallinn-learning** [Seraphim97/Homework06#1]
https://github.com/Seraphim97/Homework06/blob/ef7a45bef861d08587989bc47dbab4f245951a08/src/main/java/org/example/App.java#L11

Ir seems like you shared initial project without your cintibution

**Comment by Seraphim97** [comment]
fixed

**Comment by Seraphim97** [comment]
fixed, but i did tests in AppTest, is it a mistake?

**Comment by tallinn-learning** [comment]
not a mistake
